version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${ROOT_DATABASE_USER}
      - POSTGRES_PASSWORD=${ROOT_DATABASE_PASSWORD}
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    #   - ./pgscripts:/docker-entrypoint-initdb.d
    #   - ./data:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - 5432:5432

networks:
  appnet:
